### ISSUE TITLE
Cannot Gather Anything

### ISSUE THREAD

**Issue by Kirussu** [cursey/kanan#104]
Really enjoy Kanan for the simplicity, but whenever I run it I am not able to gather anything. I try to gather homestead stones and my character is stuck doing the animation forever until i cancel the skill. This happens with every type of gathering such as hoeing potatoes or sheering sheep. Not sure what i'm doing wrong as I havent seen anyone with this issue anywhere.

**Comment by Aahzmandius** [comment]
I've actually seen this one myself sometimes, not sure on the exact scenario, but I know using harvest song fixes it (temporarily) and allows gathering like normal.  Never bothered to track down what caused it, not even sure if it's kanan or data folder mods, since I normally use harvest song anyway for faster gathers.

**Comment by cursey** [comment]
Has it always been like that since you started using kanan and how long ago did you start using it? Just so you are aware, I am able to harvest perfectly fine and I use kanan in its default configuration, with the only data folder modifications (put inside kanan's data folder) being the blank sounds for animals.

**Comment by Kirussu** [comment]
I'm not sure when it started previously, but as a test, I reinstalled mabinogi and Kanan and went to harvest a homestead stone and it let me do it one time, but after that it was stuck again. I havent messed with any files in the kanan folder and the program files for mabi are default as well.

**Comment by Rydian** [comment]
Which server are you on and what's your name so I can go check it out?

**Comment by Kirussu** [comment]
I'm on Alexina and my name is Kamidachi

**Comment by kthyp** [comment]
The same is happening to me. I also tried to disable AlwaysCollectingTrans and UnCapAutoproduction but that didn't fix it either. Happened on fresh installs on different computers using different internet connections.

Collecting water and hoeing are definitely not working for me. I was able to fix it temporarily with a gathering speed potion.

Baramii:Mari

**Comment by cursey** [comment]
Disabling `ClientSideDevCat.js` fixed a **completely unrelated** issue for another user. Would you mind testing if disabling that script also fixes your gathering bug?

**Comment by Kirussu** [comment]
I disabled it and its fixed! thank you guys so much for your help. Just curious, what does ClientSideDevCat.js do besides stop me from harvesting anything?
