### ISSUE TITLE
Bitmap Text

### ISSUE THREAD

**Issue by Azurealistic** [cursey/kanan#11]
Small issue I noticed with the bitmap text is that some of the text isn't converted to Bitmap, such as the buff effects, party member has moved to this channel, etc. The dragon contribution that popsup in the the top right. As well as enchant names. Like the enchant info is bitmap, but the name of it is still in text.

Is it possible for it to be fixed?

**Comment by cursey** [comment]
Yeah, I'll fix it.

**Comment by Blade3575** [comment]
I would appreciate it if Bitmap was removed, as it was taken without permission from my work.

**Comment by Azurealistic** [comment]
@Blade3575 I honestly think you should simply just go, okay, she attributed me and stuff. And I'm sure Kanan won't be adding more stuff from Abyss as you asked. But bitmap is honestly NEEDED for a lot of people to not have lag, such as myself, and having that removed is going to be an issue.

**Comment by Blade3575** [comment]
@annabelle52 You could always just wait for Abyss to be fixed as well. The problem is the theft of my intellectual property. I'm not saying she's the one at fault since from what I remember, someone else said my project was dead. However, the problem the remains.

As long as the edit remains the same, the search and/or patch, then there's going to be a problem.

**Comment by cursey** [comment]
I removed any patterns I reversed from Abyss.

Back on topic, I will still fix the issues @annabelle52 in a bit.

**Comment by Blade3575** [comment]
I'll leave this here, though it's posted elsewhere since it does involve this project:

"Did you obtain the bytes used to replace from Abyss as well? I would guess yes since you obtained the searching pattern from Abyss. Using direct addresses instead of patterns wouldn't necessarily deter the fact that the patch itself is still from Abyss."

**Comment by cursey** [comment]
Fixed @annabelle52 issue.
