### ISSUE TITLE
Finding Strings in IDA

### ISSUE THREAD

**Issue by ghost** [cursey/kanan#42]
I believe the client is packed, which is probably why I don't get anything in IDA, 
so I just wanted to ask @cursey if you would be willing to go over how unpack it in order to open the client up in IDA?

**Comment by cursey** [comment]
Just dump it while its running because at that point its been unpacked.

**Comment by cursey** [comment]
Oh I should add that since it is packed IDA won't be able to determine the sections (like, .data and .rdata) so you need to let IDA search the entire dump for possible strings which results in a lot of things that look like strings, but aren't.

**Comment by ghost** [comment]
Thanks, I was able to dump it using [https://technet.microsoft.com/en-us/sysinternals/dd996900.aspx ProcDum] and open it in IDA as a binary file.
But how do I find xrefs to the string? I don't see any obvious way how.
For example, I'm trying to follow the comments in ChatAllowSameMsg.js.

**Comment by cursey** [comment]
Open the string subview, find the string and press the x button to view xrefs.  You need to make sure the string subview shows unicode strings and  stuff.  I plan on making a more detailed guide on the projects wiki.

**Comment by cursey** [comment]
You can also use CE by just searching for the unicode string and looking at what accesses it.  This is the same as viewing IDA's xrefs except you need to make the text appear in game.

**Comment by ghost** [comment]
I tried using CE, and attaching the debugger works.
However, when it ends up accessing the address, it just crashes Mabi and nothing shows up in the access window.

**Comment by cursey** [comment]
Change the CE's debugger settings to use VEH, and use the 64-bit version is what I do.

**Comment by ghost** [comment]
Ah, that was it. Thanks! :+1:

**Comment by Poshwosh** [comment]
Can I have some clarifications regarding the topic @cursey 
1.  Do you dump client.exe through task manager, procdump, or you used another method? Does it matter?
2. x32 or x64? Does it matter?
3. When I load the dump file with IDA, there's 2 options, windows report and binary file, I chose binary file because the first one did not load memory, is this correct?
4. Is it supposed to take 5+ hours to analyze?! I managed to find the "code.interface.window.main_chat.msg_omit_same" string, but I can't properly xref it because the location wasn't analyzed yet.

**Comment by cursey** [comment]
1. I don't think it matters.
2. 32-bit since mabi is 32-bit.
3. Try both? 
4. Depends. Takes like 15 minutes for me on the latest IDA. The dump isn't a full dump of the processes address space though, just of `Client.exe`. If you're dumping the entire address space that's a lot more for it to analyze.

**Comment by Poshwosh** [comment]
So that's why it's been taking so long, damn thing reached 6gb. Just the strings alone take me 15 minutes. How do I go about dumping just the Client.exe then?
