### ISSUE TITLE
Request: Disable Nagle directly through patcher

### ISSUE THREAD

**Issue by blookvoodow** [cursey/kanan#47]
It would be greatly appreciated if kanan is able to disable nagle directly. It'll be a great help to those who are on windows 10 or use proxy.

**Comment by Poshwosh** [comment]
I would love this as well, as a fellow eurofag I have to use a proxy to play Mabinogi to actually have fun. 

There is a very noticeable latency difference between Kanan and Abyss, it could be that proxies (mudfish, wtfast) have their own internet entries and that the TCPNoDelay values don't affect it, I don't know, it's just a guess.

Whatever the case, is it even possible to disable Nagle Algorithm with just memory editing?

**Comment by cursey** [comment]
Uhh, I can intercept socket creation and set `TCP_NODELAY` to true (which disables nagle). I might need to intercept `setsockopt` as well to make sure the game doesn't unset `TCP_NODELAY`. That should do it.

**Comment by cursey** [comment]
I've added what I think should be the correct way of doing it but since I have nagle disabled globally on my computer I can't easily test it. Let me know if it works please! The best way to let me know if it works is by running kanan in debug mode and pasting the output of any lines labled `DisableNagle.js` here, and giving me your own personal opinion if it seems like its working.

**Comment by cursey** [comment]
I got confirmation that I fixed it.
