### ISSUE TITLE
Request: BorderlessWindowedMode alternative with taskbar

### ISSUE THREAD

**Issue by Warsen** [cursey/kanan#51]
I really would like a version of BorderlessWindowedMode which sizes the window to the desktop but does not go over the task bar so that users can easier multi-task and multi-client

I tried to write this up myself, but failed due to the fact that I'm unable to figure out where the problem lies. I get a "TypeError: expected NativePointer object" message when I insert this stuff into the existing script. The location given for the error's location seems to be in a temporary file which is most likely a merged script file: I'm unprepared to debug.

```
var SystemParametersInfo = new NativeFunction(getProcAddress('User32.dll', 'SystemParametersInfo'),
        'int', ['uint', 'uint', 'pointer', 'uint'], 'stdcall');
var SPI_GETWORKAREA = 0x0030;
var rect = Memory.alloc(16);
var succ = SystemParametersInfo(SPI_GETWORKAREA, 0, rect, 0);
var left = Memory.readInt(rect);
var top = Memory.readInt(rect.add(4));
var right = Memory.readInt(rect.add(8));
var bottom = Memory.readInt(rect.add(12));
```

I could try harder to figure this out, but I think the task can be better done by someone already familiar with Frida. Please do and thank you.

**Comment by cursey** [comment]
Yeah sorry that error it gives isn't very useful. Here's a tip. The line number shown by the error is accurate for non-coalesced scripts if you subtract the # of lines in `Defaults.js` + 4. So `real line number = reported line number - # of lines in Defaults.js - 4`.  _The 4 isn't some random magic number either, `kanan.py` prepends 4 variables before `Defaults.js` (debug, testing, verbose and path)._

Anyway, the problem you're having is because there are two versions of `SystemParametersInfo`. An ANSI version called `SystemParametersInfoA` and a Unicode version called `SystemParametersInfoW`.  You can find this information near the bottom of Microsoft's documentation on the function.

I also prefer your way of doing it over it taking the entire screen, so I've gone ahead and made it the default behavior of `BorderlessWindowedMode.js`. Hope you are alright with that.

**Comment by Warsen** [comment]
Hey thanks, It works shockingly better than I expected, I thought maybe there would be a border problem somewhere and yet here it worked.

I recommend that you use all 4 integers of the rectangle to set the new window position because it's possible for an end user to unlock their task bar and drag it to one of the other 3 sides of their display. I tried this out on Windows 10, I right clicked task bar, unchecked "Lock the taskbar", left clicked and dragged it to the top of the screen where it snapped to the top. then when I run the game with your patcher, the game windowis positioned itself over the taskbar (and the entire display to my surprise, I expected a taskbar-shaped empty space below but it didn't happen).

It's not a big deal. I personally would never do something ridiculous such as resize or move my task bar, but a prior Linux user might. Using 'left' and 'top' instead of 0, 0 would be an improvement.

**Comment by cursey** [comment]
Oh, good point!

**Comment by Warsen** [comment]
Oh. I realized why there wasn't an empty space underneath the game window in my scenario. right and bottom are absolute positions, you'll want the parameters to be
x = left
y = top
width = right - left
height = bottom - top

**Comment by cursey** [comment]
Should work fine now.
