### ISSUE TITLE
NoBlackBars.js patching with same byte

### ISSUE THREAD

**Issue by milktao** [cursey/kanan#69]
NoBlackBars is replacing the push 01 with 01

**Comment by cursey** [comment]
![fp](https://cloud.githubusercontent.com/assets/5798459/18330714/0764eaec-750f-11e6-9907-671afcb55cf5.jpg)

**Comment by Poshwosh** [comment]
I always wondered why the bars still show...

**Comment by Poshwosh** [comment]
The correct mod seems to be 00 or change the 74 to eb. Not sure if I should pull, you probably already did it

Edit: To add to the facepalm, it does the exact same thing as HideNPCCurtains.js :laughing:

**Comment by milktao** [comment]
xD I went the 74 to jmp method but should I even make a pull? Seeing as its redundant with HideNPCCurtains functioning, hmm regardless I'll make a pull, Kanan you decide xD

**Comment by Coziestest** [comment]
The transcription error was mea culpa. Sorry about that!
It was indeed supposed to 00 be instead:

```
// Hide NPC Curtains During NPC Conversations And Cutscenes (Step29)

var pattern = scan('8B 8E F8 00 00 00 85 C9 74 07 6A 01 E8 ?? ?? ?? ?? 8B 0D');

patch(pattern.add(11), 0x00);
```

On a somewhat related note, was this one ever released here? Maybe under a different guise?:

```
// Disable Anamorphic Widescreen in Cutscenes (Step29)

var pattern1 = scan('38 06 74 1B');
var pattern2 = scan('0F B7 ?? ?? 50 57 57 57 E8 ?? ?? ?? ?? 84 C0 0F 84');

patch(pattern1.add(2), 0xEB);
patch(pattern2.add(15) [0x90, 0xE9]);
```

Either way, I imagine it would be difficult to notice when all the cutscenes are skipped anyway.

[NoMatteBox.js.zip](https://github.com/cursey/kanan/files/461257/NoMatteBox.js.zip)

**Comment by cursey** [comment]
So, we have two scripts that do essentially the same exact thing. `HideNPCCurtains.js` patches the function that gets called, and `NoBlackBars.js` patches one of the six places that function gets called...  

Since `HideNPCCurtains.js` patches the actual function I think it's the one we should keep.

Thoughts?

**Comment by Rydian** [comment]
Function:
(+) Works for all cases using that function.
(+) More likely to survive updates in general.
(-) May cause issues where it's called when not intended.

Call: 
(+) Works for just one specific use case instead of all.
(-) Less likely to survive updates.

So if all cases are desired and there's no graphical issues with it always being the modified copy, I vote stick with the function patch for people who want this removed in general.

**Comment by Poshwosh** [comment]
I thought to myself maybe HideNPCCurtains only applies it to NPCs and skips over the ones in cutscenes, nope, looks like they do the same thing.

I'd go for function too based on Rydian's facts.

**Comment by cursey** [comment]
Went with removing the script that patched the call and kept the script that patched the function. 
Let me know if this causes any issues but I don't think it will.
